# This is a basic workflow to help you get started with Actions

name: Bot

# Controls when the workflow will run
on:
    
  schedule:
    - cron: '*/6 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
