# This is a basic workflow to help you get started with Actions

name: Bot

# Controls when the workflow will run
on:
  push:
    branches:
    - main
    
  schedule:
    - cron: '*/6 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        
        - name: Every time
          run: echo "This step will always run"
          
        - name: Set up Python3.9
          uses: actions/setup-python@v1
          with: 
            python-version: 3.9
        
        - name: install lib
          run: pip install -r ../gitActions/requirements.txt
          
        - name: working
          run: python ../gitActions/emailTest.py
