# This is a basic workflow to help you get started with Actions

name: Bot

# Controls when the workflow will run
on:
    
  schedule:
    - cron: '*/6 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
        - uses: action/checkout@v1
        
        - name: Every time
          run: echo "This step will always run"
          
        - name: Set up Python3.9
          uses: action/setup-python@v1
          with: 
            python-version: 3.9
        
        - name: install lib
          run: pip install -r ./requirements.text
          
        - name: working
          run: run python ./emailTest.py
