# This is a basic workflow to help you get started with Actions

name: Bot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
    
  schedule:
    - cron: '0/6 0-23 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
